import{MYSQL_CORE,MYSQL_EXPLORER,unwrapMysqlResponse,type ConnectionSnapshot}from'@itharbors/mysql-contracts';
import{fitRelationshipViewport,layoutRelationshipGraph,renderRelationshipView,zoomRelationshipViewport,type RelationshipGraph,type RelationshipViewport}from'./relationship-view.js';
type Context={message:{request(plugin:string,method:string,input?:unknown):Promise<unknown>};panel:{openPanel(name:string):unknown}};
let context:Context|undefined;let root:HTMLElement|null=null;let connection:ConnectionSnapshot|null=null;let graph:RelationshipGraph|null=null;let viewport:RelationshipViewport={x:32,y:32,scale:1};let query='';let error:string|null=null;let sequence=0;let schemaRevision=0;
const definition={async mount(ctx:Context){context=ctx;root=document.querySelector('#panel-root');if(!root)throw new Error('Panel root element #panel-root not found');reset();render();const current=++sequence;try{const next=await core<ConnectionSnapshot>('getConnectionState');if(current!==sequence)return;connection=next;schemaRevision=next.schemaRevision;if(next.connected)await loadGraph();else render();}catch(e){if(current===sequence)setError(e);}},unmount(){sequence++;root?.replaceChildren();root=null;context=undefined;reset();},methods:{async onConnectionChanged(v:unknown){if(!isConnection(v))return;connection=v;schemaRevision=v.schemaRevision;graph=null;viewport={x:32,y:32,scale:1};sequence++;if(v.connected)await loadGraph();else render();},async onSchemaChanged(v:unknown){if(!isRevision(v)||v.connectionRevision!==connection?.connectionRevision||v.schemaRevision===schemaRevision)return;schemaRevision=v.schemaRevision;await loadGraph(true);},async onDataChanged(_v:unknown){}}};export default definition;
function reset(){connection=null;graph=null;viewport={x:32,y:32,scale:1};query='';error=null;schemaRevision=0;sequence++;}
async function loadGraph(keepWarm=false){if(!connection?.connected)return;const connectionRevision=connection.connectionRevision;const current=++sequence;if(!keepWarm)graph=null;render();try{const next=await core<RelationshipGraph>('getRelationshipGraph');if(current!==sequence||connectionRevision!==connection?.connectionRevision)return;graph=next;error=null;}catch(e){if(current!==sequence)return;setError(e,false);}render();}
async function openTable(name:string){if(!context||!connection)return;await context.message.request(MYSQL_EXPLORER,'selectObject',{connectionRevision:connection.connectionRevision,objectName:name});context.panel.openPanel('@itharbors/mysql-schema.schema');}
async function core<T>(method:string):Promise<T>{if(!context)throw new Error('关系图尚未挂载');return unwrapMysqlResponse<T>(await context.message.request(MYSQL_CORE,method));}
function render(){if(!root)return;root.innerHTML='<main class="workspace"><header class="workspace-heading"><div class="object-identity"><span class="object-kind">数据库</span><h1 class="object-title"></h1></div></header><section class="view-host"></section><footer class="status-deck"><div role="status" aria-live="polite"></div><div class="error-slot"></div></footer></main>';root.querySelector<HTMLElement>('.object-title')!.textContent=connection?.database??'全库关系图';const host=root.querySelector<HTMLElement>('.view-host')!;const status=root.querySelector<HTMLElement>('[role="status"]')!;status.textContent=error?'读取关系图失败':graph?`${graph.tables.length} 张表 · ${graph.relationships.length} 条关系`:connection?.connected?'正在读取关系图…':'等待连接 MySQL 数据库';if(error){host.innerHTML=`<div class="empty-state error" role="alert"><span>${escape(error)}</span><button data-action="retry">重试</button></div>`;host.querySelector('button')?.addEventListener('click',()=>void loadGraph());return;}if(!connection?.connected){host.innerHTML='<div class="empty-state">请先连接 MySQL 数据库。</div>';return;}if(!graph){host.innerHTML='<div class="empty-state">正在读取关系图…</div>';return;}if(graph.tables.length===0){host.innerHTML='<div class="empty-state">数据库中没有可展示的表。</div>';return;}const view=renderRelationshipView({graph,viewport,query,onViewportChange:v=>{viewport=v;},onOpenTable:n=>void openTable(n)});view.removeAttribute('role');view.removeAttribute('aria-labelledby');view.setAttribute('aria-label','MySQL 表关系图');const toolbar=view.querySelector<HTMLElement>('.relationship-toolbar')!;const search=document.createElement('input');search.type='search';search.placeholder='搜索表';search.setAttribute('aria-label','搜索关系图中的表');search.value=query;search.addEventListener('input',()=>{query=search.value;render();queueMicrotask(()=>root?.querySelector<HTMLInputElement>('input[type="search"]')?.focus());});const zoomOut=button('−','缩小',()=>zoom(1/1.1));const zoomIn=button('+','放大',()=>zoom(1.1));const fit=button('适应窗口','适应窗口',fitView);toolbar.prepend(search,zoomOut,zoomIn,fit);host.append(view);}
function button(label:string,aria:string,handler:()=>void){const b=document.createElement('button');b.type='button';b.textContent=label;b.setAttribute('aria-label',aria);b.addEventListener('click',handler);return b;}
function fitView(){if(!graph)return;const canvas=root?.querySelector<HTMLElement>('.relationship-canvas');viewport=fitRelationshipViewport(layoutRelationshipGraph(graph),canvas?.clientWidth||960,canvas?.clientHeight||640);render();}
function zoom(factor:number){const canvas=root?.querySelector<HTMLElement>('.relationship-canvas');viewport=zoomRelationshipViewport(viewport,factor,{x:(canvas?.clientWidth||960)/2,y:(canvas?.clientHeight||640)/2});render();}
function setError(v:unknown,rerender=true){error=v instanceof Error?v.message:String(v);if(rerender)render();}
function isRevision(v:unknown):v is {connectionRevision:number;schemaRevision:number}{return typeof v==='object'&&v!==null&&Number.isInteger((v as any).connectionRevision)&&Number.isInteger((v as any).schemaRevision)}function isConnection(v:unknown):v is ConnectionSnapshot{return isRevision(v)&&typeof(v as any).connected==='boolean'}function escape(v:string){return v.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}as Record<string,string>)[c]);}
