export default {
  appId: 'com.itharbors.desktop',
  productName: 'ITHARBORS',
  electronVersion: '31.7.7',
  directories: { app: 'packages/desktop', output: 'dist/desktop-release' },
  files: ['package.json', 'dist/**/*'],
  extraResources: [{ from: 'dist/desktop-runtime', to: 'runtime' }],
  asar: true,
  asarUnpack: ['node_modules/better-sqlite3/**/*.node'],
  npmRebuild: true,
  electronUpdaterCompatibility: '>=2.16',
  generateUpdatesFilesForAllChannels: true,
  artifactName: '${productName}-${version}-${arch}.${ext}',
  mac: {
    category: 'public.app-category.developer-tools',
    target: [{ target: 'dmg', arch: ['arm64'] }, { target: 'zip', arch: ['arm64'] }],
    hardenedRuntime: true,
    gatekeeperAssess: false,
    entitlements: '../../build/entitlements.mac.plist',
    entitlementsInherit: '../../build/entitlements.mac.plist',
    notarize: true,
  },
  publish: [{ provider: 'github', owner: 'itharbors', repo: 'harbors' }],
};
