export default {
  appId: 'com.itharbors.desktop',
  productName: 'ITHARBORS',
  electronVersion: '43.2.0',
  directories: { app: 'packages/desktop', output: 'dist/desktop-release' },
  files: [
    'package.json',
    'dist/**/*',
    '!node_modules/@itharbors/native-credential-vault/{src,scripts,tests}/**/*',
    '!node_modules/@itharbors/native-credential-vault/{binding.gyp,index.d.ts}',
  ],
  extraResources: [{ from: 'dist/desktop-runtime', to: 'runtime' }],
  asar: true,
  asarUnpack: [
    'node_modules/@itharbors/native-credential-vault/**/*.node',
    'node_modules/better-sqlite3/**/*.node',
  ],
  npmRebuild: true,
  electronUpdaterCompatibility: '>=2.16',
  generateUpdatesFilesForAllChannels: true,
  artifactName: '${productName}-${version}-${arch}-mac.${ext}',
  dmg: {
    artifactName: '${productName}-${version}-${arch}.${ext}',
  },
  mac: {
    category: 'public.app-category.developer-tools',
    target: [{ target: 'dmg', arch: ['arm64'] }, { target: 'zip', arch: ['arm64'] }],
    hardenedRuntime: true,
    gatekeeperAssess: false,
    entitlements: 'build/entitlements.mac.plist',
    entitlementsInherit: 'build/entitlements.mac.plist',
    notarize: true,
  },
  publish: [{ provider: 'github', owner: 'itharbors', repo: 'harbors' }],
};
