export const spaceDirs = [
    [
        './basic/panel',
    ],
    [
        './framework/kit',
        './framework/plugin',
        './framework/profile',
        './framework/window',
    ],
    [
        './startup',
    ],
    [
        '../plugin/panel',
        '../plugin/message',
        '../plugin/main-window',
    ],
];
