#!/usr/bin/env bash

test_skill_layout_and_contract() {
  test -f "$SKILL_SOURCE/SKILL.md" || fail 'SKILL.md is missing'
  test -f "$SKILL_SOURCE/agents/openai.yaml" || fail 'agents/openai.yaml is missing'
  test -x "$SOURCE_START" || fail 'start-kit-change.sh is missing or not executable'
  test -x "$SOURCE_FINISH" || fail 'finish-kit-change.sh is missing or not executable'
  test -x "$SOURCE_RELEASE" || fail 'release-kit.sh is missing or not executable'
  assert_contains "$(sed -n '1,8p' "$SKILL_SOURCE/SKILL.md")" 'name: kit-workflow'
  skill=$(cat "$SKILL_SOURCE/SKILL.md")
  assert_contains "$skill" 'main:kits/<kit>'
  assert_contains "$skill" 'origin/main'
  assert_contains "$skill" 'kit/<kit>/v<version>'
  assert_not_contains "$skill" 'origin/kit/<kit>'
  assert_not_contains "$skill" 'product branch'
  assert_contains "$skill" '背景、目标、范围、非目标、验收、约束'
  assert_contains "$skill" 'feature`/`bug`/`optimize`/`docs`/`refactor`/`test`/`chore'
  assert_contains "$skill" '立即填写 `task.md`'
  assert_contains "$skill" '截止时间、负责人授权和已投入时间都不是跳过 Task 的例外'
  assert_contains "$skill" '`.work/` 默认不提交'
  assert_contains "$skill" '`status.json` 只由 `task:status` CLI 管理'
  assert_contains "$skill" '先完成 `summary.md`'
  assert_contains "$skill" '`--ready-for-pr`'
  assert_contains "$skill" '回写 PR 号、自动提交并二次 push'
  assert_contains "$skill" '`rewind`'
  assert_contains "$skill" 'GitHub PR 已 merged'
  assert_contains "$skill" 'latest head commit 的 repository-required checks'
  assert_contains "$skill" '三份 Task 正式文件已在 `main`'
  assert_contains "$skill" '归档当前 Codex 会话'
  assert_contains "$skill" '先读 `task.md` 和 `status.json`'
  assert_contains "$skill" '跨机或跨环境'
  assert_contains "$skill" '三份 Task 正式档案'
  assert_contains "$skill" '不授权修改其他 Task、其他 Kit 或仓库共享代码'
  assert_contains "$skill" 'Task 生命周期不自动授权 Kit 发布'
  assert_contains "$(cat "$SKILL_SOURCE/agents/openai.yaml")" 'display_name: "Kit Workflow"'
  assert_contains "$(cat "$SKILL_SOURCE/agents/openai.yaml")" 'main'
  grep -Fq '"test:kit-workflow"' "$REPO_SOURCE/package.json" || fail 'package test script is missing'
  grep -Fq '"kit:boundary"' "$REPO_SOURCE/package.json" || fail 'kit:boundary script is missing'
  grep -Fq '"test:kit-boundary"' "$REPO_SOURCE/package.json" || fail 'test:kit-boundary script is missing'
}

run_contract_tests() { run_case 'skill layout and active contract' test_skill_layout_and_contract; }
