export const mysqlCopy = {
  brand: {
    title: 'MySQL 工作台',
    subtitle: '直连数据库',
  },
  connection: {
    host: '主机',
    port: '端口',
    user: '用户名',
    password: '密码',
    database: '数据库',
    connect: '连接',
    disconnect: '断开连接',
    refresh: '刷新数据库',
    connectedLabel: '已连接',
    disconnectedLabel: '未连接',
    credentialsLocal: '凭据仅保留在当前服务端会话中。',
    tlsVerified: 'TLS 已验证',
    unknownVersion: '未知版本',
    prompt: '请输入 MySQL 连接信息以开始。',
    connected: (endpoint: string | null, database: string | null) => `已连接到 ${endpoint}/${database}。`,
    disconnected: '连接已断开。',
    refreshed: '数据库元数据已刷新。',
  },
  objects: {
    title: '数据库对象',
    filterLabel: '筛选对象',
    filterPlaceholder: '筛选表和视图',
    noneSelected: '未选择对象',
    workspace: 'MySQL 数据库对象工作区',
    tables: '表',
    views: '视图',
    table: '表',
    view: '视图',
    database: '数据库',
    connectPrompt: '连接后即可查看表和视图。',
    empty: '此数据库没有表或视图。',
    noMatch: '没有符合筛选条件的对象。',
    choose: '请选择要查看的表或视图。',
    selected: (name: string) => `已选择 ${name}。`,
  },
  capability: {
    readonlyView: '此视图为只读；如需执行数据库定义的视图操作，请使用 SQL。',
    noPrimaryKey: '此表没有可用的主键。可以新增记录，但无法编辑或删除。',
  },
  tabs: {
    data: '数据',
    schema: '结构',
    sql: 'SQL',
  },
  actions: {
    add: '新增记录',
    edit: '编辑',
    delete: '删除',
    cancel: '取消',
    save: '保存更改',
  },
  welcome: {
    eyebrow: '服务端 → 数据库 → 记录',
    title: '查看 MySQL，同时保留 SQL 的透明度。',
    description: '连接一个数据库，浏览结构、编辑带主键的记录，或有意识地执行一条 SQL 语句。',
    steps: [
      ['连接', '凭据保留在当前服务端进程中。'],
      ['查看', '读取表、视图、键、索引和外键。'],
      ['操作', '对记录执行受约束的增删改查；在 SQL 页签中直接执行语句。'],
    ],
  },
  data: {
    loading: '正在加载记录…',
    notLoaded: '尚未加载记录数据。',
    empty: '此对象中没有记录。',
    range: (start: number, end: number, total: number) => `${start}–${end} / ${total.toLocaleString()} 条记录`,
    rowsPerPage: '每页行数',
    pageSize: (size: number) => `${size} 行`,
    previous: '上一页',
    next: '下一页',
    loadedPage: (page: number) => `已加载第 ${page} 页。`,
    unchanged: '记录内容没有变化。',
    added: '记录已新增。',
    updated: '记录已更新。',
    deleted: '记录已删除。',
    confirmDelete: (name: string | null) => `确定从 ${name} 删除所选记录吗？`,
  },
  schema: {
    notLoaded: '尚未加载结构。',
    columns: '字段',
    name: '名称',
    type: '类型',
    nullable: '可空',
    defaultValue: '默认值',
    extra: '附加信息',
    yes: '是',
    no: '否',
    generated: '生成字段',
    indexes: '索引',
    noIndexes: '没有索引。',
    foreignKeys: '外键',
    noForeignKeys: '没有外键。',
    definitionSql: '定义 SQL',
  },
  sql: {
    label: '单条语句 · 直接执行',
    run: '执行语句',
    truncated: '结果预览在 500 行处截断。',
    affected: (count: number) => `影响 ${count} 行`,
    mutationMeta: (insertId: string, warningStatus: number) => `插入 ID ${insertId} · 警告 ${warningStatus}`,
    returnedStatus: (count: number, elapsed: string) => `返回 ${count} 行 · ${elapsed}`,
    affectedStatus: (count: number, elapsed: string) => `影响 ${count} 行 · ${elapsed}`,
  },
  dialog: {
    insertMode: '新增',
    updateMode: '更新',
    add: '新增记录',
    edit: '编辑所选记录',
    include: (name: string) => `包含 ${name}`,
    valueType: (name: string) => `${name} 值类型`,
  },
  status: {
    working: '处理中…',
  },
  errors: {
    panelNotMounted: 'MySQL 工作台尚未挂载',
  },
  validation: {
    integer: '请输入十进制整数',
    decimal: '请输入有效的小数',
    real: '请输入有限实数',
    json: '请输入有效的 JSON',
    temporal: (type: string) => `请输入 ${type} 值`,
  },
} as const;
