export const sqliteCopy = {
  brand: {
    aria: 'SQLite 工作台',
    subtitle: '工作台',
  },
  connection: {
    path: '数据库路径',
    open: '打开',
    create: '创建',
    refresh: '刷新',
    close: '关闭',
    disconnected: '尚未连接',
    enterPath: '请输入本地 SQLite 数据库路径。',
    opened: '数据库已打开',
    created: '数据库已创建',
    closed: '数据库已关闭',
    refreshed: '数据库已刷新',
  },
  objects: {
    title: '数据库对象',
    workspace: '数据库对象工作区',
    openPrompt: '打开数据库后即可查看其中的表和视图。',
    empty: '此数据库还没有表或视图，可使用 SQL 创建。',
    tables: '表',
    views: '视图',
    table: '表',
    view: '视图',
    database: '数据库',
    emptyDatabase: '空数据库',
    connectDatabase: '请连接数据库',
    readonlyView: '只读视图',
    noneSelected: '尚未选择数据库对象。',
    selected: (name: string) => `已选择 ${name}`,
  },
  tabs: {
    data: '数据',
    schema: '结构',
    sql: 'SQL',
  },
  welcome: {
    label: '本地 SQLite',
    title: '打开文件，查看真实数据。',
    description: '检查结构、分页浏览记录、精确编辑数据，或逐条执行 SQL 语句。',
    cells: ['结构', '记录', '键', '查询'],
  },
  data: {
    add: '新增记录',
    edit: '编辑',
    delete: '删除',
    loading: '正在加载记录',
    loadingSelected: '正在加载所选对象…',
    empty: '此表暂无记录，可新增第一条记录。',
    emptyPage: '本页没有记录。',
    rowSelector: (row: number) => `选择第 ${row} 行`,
    records: (count: number) => `${count.toLocaleString()} 条记录`,
    rows: (count: number) => `${count.toLocaleString()} 行`,
    added: '记录已新增',
    updated: '记录已更新',
    deleted: '记录已删除',
    confirmDelete: '确定删除所选记录吗？此操作无法撤销。',
  },
  pagination: {
    previous: '上一页',
    next: '下一页',
    rowsPerPage: '每页行数',
    pageSize: (size: number) => `${size} / 页`,
  },
  schema: {
    loading: '正在加载结构…',
    columns: '字段',
    indexes: '索引',
    definition: '定义',
    name: '名称',
    type: '类型',
    flags: '标记',
    defaultValue: '默认值',
    noIndexes: '未声明索引。',
    columnCount: (count: number) => `${count} 个字段`,
  },
  sql: {
    run: '执行语句',
    hint: '单条语句 · ⌘/Ctrl + Enter',
    emptyResult: '执行语句后，结果将显示在这里。',
    truncated: '仅显示前 500 行。',
    changed: '行已变更',
    lastRowid: (value: string) => `最后 rowid ${value}`,
    resultRows: (count: number, elapsedMs: number) => `返回 ${count} 行 · ${elapsedMs} ms`,
    changedRows: (count: number, elapsedMs: number) => `影响 ${count} 行 · ${elapsedMs} ms`,
  },
  dialog: {
    table: '表',
    add: '新增记录',
    edit: '编辑记录',
    fieldType: (name: string) => `${name} 类型`,
    fieldValue: (name: string) => `${name} 值`,
    useDefault: '使用默认值',
    cancel: '取消',
    save: '保存更改',
  },
  status: {
    initial: '未连接数据库',
    working: '处理中…',
    online: '外键已启用 · 忙碌超时 5 秒',
    offline: '离线',
    advice: '请检查数据库路径、锁定状态或 SQL 后重试。',
  },
  errors: {
    panelNotMounted: 'SQLite 工作台尚未挂载',
    selectTable: '请先选择表',
    readonly: '当前数据库对象为只读',
    selectRow: '请选择要编辑的记录',
  },
  validation: {
    integer: '请输入十进制整数',
    real: '请输入有限实数',
  },
} as const;
