export type ThemeTokens = Record<`--ce-${string}`, string>;

export const DEFAULT_THEME_TOKENS: ThemeTokens = {
  '--ce-color-neutral-0': '#0f1115',
  '--ce-color-neutral-1': '#16181d',
  '--ce-color-neutral-2': '#1c2027',
  '--ce-color-neutral-3': '#20252d',
  '--ce-color-neutral-4': '#2a2f39',
  '--ce-color-neutral-5': '#3a4150',
  '--ce-color-neutral-6': '#f3f5f7',
  '--ce-color-accent-500': '#4c9ffe',
  '--ce-color-success-500': '#32c48d',
  '--ce-color-warning-500': '#ce9178',
  '--ce-color-danger-500': '#ff6b6b',
  '--ce-space-1': '4px',
  '--ce-space-2': '8px',
  '--ce-space-3': '12px',
  '--ce-space-4': '16px',
  '--ce-space-5': '24px',
  '--ce-space-6': '32px',
  '--ce-radius-sm': '4px',
  '--ce-radius-md': '8px',
  '--ce-radius-lg': '12px',
  '--ce-font-size-xs': '11px',
  '--ce-font-size-sm': '12px',
  '--ce-font-size-md': '14px',
  '--ce-font-weight-normal': '400',
  '--ce-font-weight-medium': '500',
  '--ce-shadow-1': 'inset 0 1px 2px rgb(0 0 0 / 0.24)',
  '--ce-shadow-2': '0 8px 24px rgb(0 0 0 / 0.28)',
  '--ce-surface': 'var(--ce-color-neutral-1)',
  '--ce-surface-raised': 'var(--ce-color-neutral-2)',
  '--ce-surface-overlay': '#181c22',
  '--ce-surface-hover': 'var(--ce-color-neutral-3)',
  '--ce-surface-active': '#232934',
  '--ce-text-primary': 'var(--ce-color-neutral-6)',
  '--ce-text-secondary': '#c2c8d0',
  '--ce-text-muted': '#8b93a1',
  '--ce-text-on-accent': '#081120',
  '--ce-border': 'var(--ce-color-neutral-4)',
  '--ce-border-strong': 'var(--ce-color-neutral-5)',
  '--ce-accent': 'var(--ce-color-accent-500)',
  '--ce-focus-ring': 'var(--ce-color-accent-500)',
  '--ce-selection-bg': '#1f3656',
  '--ce-success': 'var(--ce-color-success-500)',
  '--ce-warning': 'var(--ce-color-warning-500)',
  '--ce-danger': 'var(--ce-color-danger-500)',
  '--ce-workbench-bg': 'var(--ce-surface)',
  '--ce-workbench-padding': '0',
  '--ce-workbench-gap': '0',
  '--ce-panel-bg': 'var(--ce-surface)',
  '--ce-panel-content-bg': 'var(--ce-surface)',
  '--ce-panel-border-color': 'var(--ce-border)',
  '--ce-panel-border-width': '1px',
  '--ce-panel-radius': 'var(--ce-radius-sm)',
  '--ce-panel-header-bg': 'var(--ce-surface-raised)',
  '--ce-panel-header-border-color': 'var(--ce-border)',
  '--ce-panel-header-border-width': '1px',
  '--ce-panel-group-border-color': 'var(--ce-border)',
  '--ce-panel-group-border-width': '1px',
  '--ce-panel-group-radius': 'var(--ce-radius-sm)',
  '--ce-tabbar-bg': 'var(--ce-surface-raised)',
  '--ce-tabbar-border-color': 'var(--ce-border)',
  '--ce-tabbar-border-width': '1px',
  '--ce-tabbar-empty-bg': 'var(--ce-tabbar-bg)',
  '--ce-tab-bg': 'transparent',
  '--ce-tab-bg-hover': 'var(--ce-surface-hover)',
  '--ce-tab-bg-active': 'var(--ce-surface-raised)',
  '--ce-tab-fg': 'var(--ce-text-secondary)',
  '--ce-tab-fg-active': 'var(--ce-text-primary)',
  '--ce-tab-separator': 'var(--ce-border)',
  '--ce-tab-active-indicator': 'var(--ce-accent)',
  '--ce-divider-color': 'var(--ce-border)',
  '--ce-divider-hover-color': 'var(--ce-divider-color, var(--ce-border))',
  '--ce-divider-active-color': 'var(--ce-accent)',
  '--ce-drop-indicator-color': 'var(--ce-divider-active-color, var(--ce-accent))',
  '--ce-drop-zone-border-color': 'var(--ce-drop-indicator-color, var(--ce-divider-active-color, var(--ce-accent)))',
  '--ce-drop-zone-fill': 'rgb(76 159 254 / 0.16)',
  '--ce-button-bg': 'var(--ce-surface-raised)',
  '--ce-button-bg-hover': 'var(--ce-surface-hover)',
  '--ce-button-bg-active': 'var(--ce-surface-active)',
  '--ce-button-border': 'var(--ce-border-strong)',
  '--ce-button-fg': 'var(--ce-text-primary)',
  '--ce-button-focus-ring': 'var(--ce-focus-ring)',
  '--ce-button-disabled-bg': '#15181d',
  '--ce-button-disabled-border': '#2b313c',
  '--ce-button-disabled-fg': '#666d79',
  '--ce-input-bg': 'var(--ce-surface-raised)',
  '--ce-input-bg-hover': 'var(--ce-surface-hover)',
  '--ce-input-bg-active': 'var(--ce-surface-active)',
  '--ce-input-border': 'var(--ce-border-strong)',
  '--ce-input-fg': 'var(--ce-text-primary)',
  '--ce-input-placeholder': '#7f8796',
  '--ce-input-focus-ring': 'var(--ce-focus-ring)',
  '--ce-input-disabled-bg': '#15181d',
  '--ce-input-disabled-border': '#2b313c',
  '--ce-input-disabled-fg': '#666d79',
  '--ce-checkbox-bg': 'var(--ce-surface-raised)',
  '--ce-checkbox-border': 'var(--ce-border-strong)',
  '--ce-checkbox-bg-checked': 'var(--ce-accent)',
  '--ce-checkbox-border-checked': 'var(--ce-accent)',
  '--ce-checkbox-check': 'var(--ce-text-on-accent)',
  '--ce-checkbox-focus-ring': 'var(--ce-focus-ring)',
  '--ce-checkbox-disabled-opacity': '0.5',
  '--ce-gray-0': 'var(--ce-color-neutral-0)',
  '--ce-gray-100': 'var(--ce-color-neutral-1)',
  '--ce-gray-200': 'var(--ce-color-neutral-2)',
  '--ce-gray-300': 'var(--ce-color-neutral-3)',
  '--ce-gray-400': 'var(--ce-color-neutral-4)',
  '--ce-gray-500': '#cccccc',
  '--ce-gray-600': 'var(--ce-color-neutral-6)',
  '--ce-font-xs': 'var(--ce-font-size-xs)',
  '--ce-font-sm': 'var(--ce-font-size-sm)',
  '--ce-font-md': 'var(--ce-font-size-md)',
  '--ce-font-lg': '16px',
  '--ce-blue': 'var(--ce-color-accent-500)',
  '--ce-green': 'var(--ce-color-success-500)',
  '--ce-red': 'var(--ce-color-danger-500)',
  '--ce-orange': 'var(--ce-color-warning-500)',
};

export function renderThemeVariables(tokens: ThemeTokens): string {
  return Object.entries(tokens).map(([token, value]) => `${token}:${value};`).join('');
}
