export const defaultMenuContributions = [
  { type: 'menu', id: 'app', labelKey: 'menu.app', order: 50, platforms: ['darwin'] },
  { type: 'menu', id: 'app/about', labelKey: 'menu.app.about', role: 'about', order: 10, platforms: ['darwin'] },
  { type: 'separator', id: 'app/sep-about', order: 20, platforms: ['darwin'] },
  { type: 'menu', id: 'app/services', labelKey: 'menu.app.services', role: 'services', order: 30, platforms: ['darwin'] },
  { type: 'separator', id: 'app/sep-services', order: 40, platforms: ['darwin'] },
  { type: 'menu', id: 'app/hide', labelKey: 'menu.app.hide', role: 'hide', order: 50, platforms: ['darwin'] },
  { type: 'menu', id: 'app/hide-others', labelKey: 'menu.app.hideOthers', role: 'hideOthers', order: 60, platforms: ['darwin'] },
  { type: 'menu', id: 'app/show-all', labelKey: 'menu.app.showAll', role: 'unhide', order: 70, platforms: ['darwin'] },
  { type: 'separator', id: 'app/sep-quit', order: 80, platforms: ['darwin'] },
  { type: 'menu', id: 'app/quit', labelKey: 'menu.app.quit', role: 'quit', order: 90, platforms: ['darwin'] },

  { type: 'menu', id: 'file', labelKey: 'menu.file', order: 100 },
  { type: 'menu', id: 'file/new-session', labelKey: 'menu.file.new', message: 'newSession', order: 110 },
  { type: 'separator', id: 'file/sep-close', order: 120 },
  { type: 'menu', id: 'file/close-window', labelKey: 'menu.file.closeWindow', role: 'close', order: 130, platforms: ['darwin'] },
  { type: 'menu', id: 'file/quit', labelKey: 'menu.file.quit', role: 'quit', order: 140, platforms: ['win32', 'linux'] },

  { type: 'menu', id: 'edit', labelKey: 'menu.edit', order: 200 },
  { type: 'menu', id: 'edit/undo', labelKey: 'menu.edit.undo', role: 'undo', order: 210 },
  { type: 'menu', id: 'edit/redo', labelKey: 'menu.edit.redo', role: 'redo', order: 220 },
  { type: 'separator', id: 'edit/sep-clipboard', order: 230 },
  { type: 'menu', id: 'edit/cut', labelKey: 'menu.edit.cut', role: 'cut', order: 240 },
  { type: 'menu', id: 'edit/copy', labelKey: 'menu.edit.copy', role: 'copy', order: 250 },
  { type: 'menu', id: 'edit/paste', labelKey: 'menu.edit.paste', role: 'paste', order: 260 },
  { type: 'separator', id: 'edit/sep-select', order: 270 },
  { type: 'menu', id: 'edit/select-all', labelKey: 'menu.edit.selectAll', role: 'selectAll', order: 280 },

  { type: 'menu', id: 'view', labelKey: 'menu.view', order: 300 },
  { type: 'menu', id: 'view/reload', labelKey: 'menu.view.reload', role: 'reload', order: 310 },
  { type: 'menu', id: 'view/toggle-devtools', labelKey: 'menu.view.toggleDevTools', role: 'toggleDevTools', order: 320 },
  { type: 'separator', id: 'view/sep-zoom', order: 330 },
  { type: 'menu', id: 'view/reset-zoom', labelKey: 'menu.view.resetZoom', role: 'resetZoom', order: 340 },
  { type: 'menu', id: 'view/zoom-in', labelKey: 'menu.view.zoomIn', role: 'zoomIn', order: 350 },
  { type: 'menu', id: 'view/zoom-out', labelKey: 'menu.view.zoomOut', role: 'zoomOut', order: 360 },
  { type: 'separator', id: 'view/sep-fullscreen', order: 370 },
  { type: 'menu', id: 'view/toggle-fullscreen', labelKey: 'menu.view.toggleFullScreen', role: 'togglefullscreen', order: 380 },

  { type: 'menu', id: 'window', labelKey: 'menu.window', order: 400 },
  { type: 'menu', id: 'window/minimize', labelKey: 'menu.window.minimize', role: 'minimize', order: 410 },
  { type: 'menu', id: 'window/zoom', labelKey: 'menu.window.zoom', role: 'zoom', order: 420, platforms: ['darwin'] },
  { type: 'separator', id: 'window/sep-front', order: 430, platforms: ['darwin'] },
  { type: 'menu', id: 'window/front', labelKey: 'menu.window.front', role: 'front', order: 440, platforms: ['darwin'] },
  { type: 'menu', id: 'window/close', labelKey: 'menu.window.close', role: 'close', order: 450, platforms: ['win32', 'linux'] },

  { type: 'menu', id: 'help', labelKey: 'menu.help', order: 500 },
  { type: 'menu', id: 'help/about', labelKey: 'menu.help.about', message: 'openAbout', order: 510, platforms: ['win32', 'linux'] },
  { type: 'menu', id: 'help/documentation', labelKey: 'menu.help.documentation', message: 'openDocumentation', order: 520 },
];

export const defaultMenuMessages = {
  'zh-CN': {
    'menu.app': 'ITHARBORS',
    'menu.app.about': '关于 ITHARBORS',
    'menu.app.services': '服务',
    'menu.app.hide': '隐藏 ITHARBORS',
    'menu.app.hideOthers': '隐藏其他',
    'menu.app.showAll': '显示全部',
    'menu.app.quit': '退出',
    'menu.file': '文件',
    'menu.file.new': '新建会话',
    'menu.file.closeWindow': '关闭窗口',
    'menu.file.quit': '退出',
    'menu.edit': '编辑',
    'menu.edit.undo': '撤销',
    'menu.edit.redo': '重做',
    'menu.edit.cut': '剪切',
    'menu.edit.copy': '复制',
    'menu.edit.paste': '粘贴',
    'menu.edit.selectAll': '全选',
    'menu.view': '视图',
    'menu.view.reload': '重新加载',
    'menu.view.toggleDevTools': '切换开发者工具',
    'menu.view.resetZoom': '实际大小',
    'menu.view.zoomIn': '放大',
    'menu.view.zoomOut': '缩小',
    'menu.view.toggleFullScreen': '切换全屏',
    'menu.window': '窗口',
    'menu.window.minimize': '最小化',
    'menu.window.zoom': '缩放',
    'menu.window.front': '全部置于顶层',
    'menu.window.close': '关闭',
    'menu.help': '帮助',
    'menu.help.about': '关于 ITHARBORS',
    'menu.help.documentation': '文档',
  },
  'en-US': {
    'menu.app': 'ITHARBORS',
    'menu.app.about': 'About ITHARBORS',
    'menu.app.services': 'Services',
    'menu.app.hide': 'Hide ITHARBORS',
    'menu.app.hideOthers': 'Hide Others',
    'menu.app.showAll': 'Show All',
    'menu.app.quit': 'Quit',
    'menu.file': 'File',
    'menu.file.new': 'New Session',
    'menu.file.closeWindow': 'Close Window',
    'menu.file.quit': 'Quit',
    'menu.edit': 'Edit',
    'menu.edit.undo': 'Undo',
    'menu.edit.redo': 'Redo',
    'menu.edit.cut': 'Cut',
    'menu.edit.copy': 'Copy',
    'menu.edit.paste': 'Paste',
    'menu.edit.selectAll': 'Select All',
    'menu.view': 'View',
    'menu.view.reload': 'Reload',
    'menu.view.toggleDevTools': 'Toggle Developer Tools',
    'menu.view.resetZoom': 'Actual Size',
    'menu.view.zoomIn': 'Zoom In',
    'menu.view.zoomOut': 'Zoom Out',
    'menu.view.toggleFullScreen': 'Toggle Full Screen',
    'menu.window': 'Window',
    'menu.window.minimize': 'Minimize',
    'menu.window.zoom': 'Zoom',
    'menu.window.front': 'Bring All to Front',
    'menu.window.close': 'Close',
    'menu.help': 'Help',
    'menu.help.about': 'About ITHARBORS',
    'menu.help.documentation': 'Documentation',
  },
};
